packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@biomejs/biome": ^2.3.11
  "@faker-js/faker": 10.2.0
  "@fast-check/vitest": ^0.2.4
  "@hookform/resolvers": ^5.2.2
  fast-check: ^4.5.3
  prettier: 3.8.1
  react-hook-form: ^7.71.1
  tailwindcss: ^4.1.18
  typescript: ^5.9.3
  vite: ^7.2.4
  zod: 4.3.1

catalogs:
  effect3:
    "@effect/experimental": ^0.58.0
    "@effect/opentelemetry": ^0.61.0
    "@effect/platform": ^0.94.2
    "@effect/platform-node": ^0.104.1
    "@effect/sql": ^0.49.0
    "@effect/sql-pg": ^0.50.1
    effect: ^3.19.15
  node25:
    "@types/node": ^25.0.9
  react19:
    "@types/react": ^19.2.0
    "@types/react-dom": ^19.2.0
    react: 19.2.0
    react-dom: 19.2.0
  vitest4:
    "@vitest/coverage-istanbul": 4.0.17
    "@vitest/coverage-v8": 4.0.17
    "@vitest/ui": 4.0.17
    vitest: 4.0.17

onlyBuiltDependencies:
  - esbuild
