packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

# -------------------------------------------------------------------------
# PNPM Catalogs
# -------------------------------------------------------------------------
# Define strict versions for dependencies used across multiple packages.
#
# Referenced in package.json as: "dependency": "catalog:"
#
# Advantages:
# 1. Single Source of Truth: Update version in ONE place for the entire repo.
# 2. Deduplication: Guarantees every package uses the exact same version.
# 3. Consistency: Prevents mismatches between apps/packages.
# -------------------------------------------------------------------------
catalog:
  typescript: ^5.9.3
  zod: 4.3.1
  vite: ^7.2.4
  prettier: 3.8.1
  tailwindcss: ^4.1.18
  "react-hook-form": ^7.71.1
  "@hookform/resolvers": ^5.2.2
  "@biomejs/biome": ^2.3.11
  "@faker-js/faker": "10.2.0"
  "@fast-check/vitest": "^0.2.4"

catalogs:
  react19:
    react: 19.2.0
    react-dom: 19.2.0
    "@types/react": ^19.2.0
    "@types/react-dom": ^19.2.0

  vitest3:
    "vitest": 4.0.17
    "@vitest/coverage-istanbul": 4.0.17
    "@vitest/coverage-v8": 4.0.17
    "@vitest/ui": 4.0.17

  node25:
    "@types/node": "^25.0.9"

  effect3:
    "effect": ^3.19.15
    "@effect/experimental": ^0.58.0
    "@effect/opentelemetry": ^0.61.0
    "@effect/platform": ^0.94.2
    "@effect/platform-node": ^0.104.1
    "@effect/sql": ^0.49.0
    "@effect/sql-pg": ^0.50.1

onlyBuiltDependencies:
  - esbuild
